-- First, ensure the table exists
CREATE TABLE IF NOT EXISTS shared_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL UNIQUE,
    gsc_property TEXT NOT NULL,
    components JSONB NOT NULL,
    filters JSONB NOT NULL,
    gsc_data JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow public read access to shared_reports" ON shared_reports;
DROP POLICY IF EXISTS "Allow public read access to shared_reports gsc_data" ON shared_reports;

-- Enable RLS
ALTER TABLE shared_reports ENABLE ROW LEVEL SECURITY;

-- Create a single comprehensive policy for public read access
CREATE POLICY "Allow public read access to shared_reports" ON shared_reports
    FOR SELECT
    USING (true);

-- Grant necessary permissions
GRANT SELECT ON shared_reports TO anon, authenticated;

-- Add index on token for faster lookups
CREATE INDEX IF NOT EXISTS shared_reports_token_idx ON shared_reports(token); 