-- Create shared_reports table if it doesn't exist
CREATE TABLE IF NOT EXISTS shared_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token UUID NOT NULL UNIQUE,
    gsc_property TEXT NOT NULL,
    components JSONB NOT NULL,
    filters JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS on shared_reports table
ALTER TABLE shared_reports ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access to shared reports
CREATE POLICY "Allow public read access to shared reports"
    ON shared_reports
    FOR SELECT
    USING (true);  -- This allows anyone to read any shared report

-- Create policy to allow authenticated users to create shared reports
CREATE POLICY "Allow authenticated users to create shared reports"
    ON shared_reports
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated'); 